server:
  port: 9080
spring:
  datasource:
    url: jdbc:postgresql://${database_host:192.168.1.114}:${database_port:5432}/${database_name:clef-workflow}
    username: ${database_user:clef-workflow}
    password: ${database_password:clef-workflow}
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        storage_engine: innodb
        enable_lazy_load_no_trans: true
  profiles:
    active: postgres